### ISSUE TITLE
Extract the HiDPI part without the custom tweaks (which look nice too!)

### ISSUE THREAD

**Issue by arthurzenika** [thapabishwa/HiDPI-awesome-wm#1]
Hi, 

I'm a awesomewm user and recently "upgraded" to an HiDPI laptop. Am have a *lot* of trouble getting it to work. So your project is really welcome, but I would love to integrate only the parts that handle font size etc and not all the tweaks you have published (thanks for that too, I'll have to find the time at some point to try out some customizations like yours). 

Could you point me to which bit of your configuration solves the HiDPI "problem" ? 

Thanks in advance.

**Comment by thapabishwa** [comment]
Thanks for letting me know. Apparently, this repo is missing some key files. The changes should be here asap.

**Comment by thapabishwa** [comment]
Hello,
The primary thing would be to copy .Xresources and .xinitrc to your ~/.
I hope that solves some of your problems.
Regarding the font size [Works If and only if you are using [awesome copycats](https://github.com/lcpz/awesome-copycats)], I recommend that you dig deeper into the rc.lua of the theme you desire to use and theme.lua relevant to the theme.
Let me know if you have other issues.
Cheers.
